### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by victorjoaoss** [PetJournal/petjournal.android#2]
https://github.com/PetJournal/product/issues/1

**Comment by victorjoaoss** [comment]
-

- [ ] ahjajka
- [ ] sjsjis

**Comment by gusoliveira21** [comment]
- [x] Definir o layout da tela de login e do SplashScreen, levando em consideração as informações e critérios de aceite descritos.
- [x] Criar os componentes da tela de login, como:
	- [x] Campo email/telefone, 
	- [x] Campo senha, 
	- [x] Botão de login,	
	- [x] Opção de lembrar minha senha
	- [x] Links para as telas de recuperação de senha e cadastro 
- [ ] Implementar a lógica para validação dos campos de email ou telefone e senha, verificando se as informações fornecidas são corretas. 
- [ ] Implementar a lógica para a opção de lembrar o login 
- [ ] Implementar a lógica para habilitar o botão de login apenas quando todas as informações necessárias forem preenchidas corretamente.
- [ ] Implementar a lógica para redirecionar o usuário para a tela de recuperação de senha ou cadastro, conforme necessário. 
- [ ] Apresentar a mensagem de erro em caso de informações incorretas no login.
- [ ] Criar o SplashScreen, definindo sua aparência e comportamento.
- [ ] Implementar a lógica para carregar os recursos necessários durante o tempo de exibição do SplashScreen.
- [ ] Integrar a SplashScreen à tela de login, exibindo-a durante o carregamento do aplicativo e redirecionando o usuário para a tela de login após o término do tempo de exibição da SplashScreen.
- [ ] Testar o aplicativo para garantir que todas as funcionalidades estejam funcionando corretamente e fazer ajustes, se necessário.
