### ISSUE TITLE
Esqueceu a Senha

### ISSUE THREAD

**Issue by victorjoaoss** [PetJournal/petjournal.android#6]
https://github.com/PetJournal/petjournal.product/issues/5

**Comment by gusoliveira21** [comment]
(em atualização)
### Layout - "Esqueceu a senha?"

> - [ ] Criar layout "Esqueceu a senha?" 
> - [ ] Botão clicado: envia o email para o back-end avisando que é para recuperar senha.
>      - recebe a resposta do back-end:
> negativo:
> - [ ] Exibe uma mensagem de erro
>      - (é válido avisar que aquele email não esta cadastrado na base de dados?)
>      - positivo: 
> - [ ] Vai para a tela "Acabamos de enviar um código de verificação para seu email"
> - [ ] Refatorar layout
> 
> - [ ] Criar a rota de comunicação com retrofit desta task
> - ajustar viewModel
> - ajustar usecase
> - ajustar data

### Layout - "Aguardando código..."

> - [ ] Criar layout "Aguardando código de verificação"
>      - Botão clicado: a pessoa nos envia o código
> - [ ] validamos o código (localmente ou pelo back-end?)
>      - positivo envia o usuario para trocar a senha
> - [ ] refatorar layout
> 
> - [ ] Criar a rota de comunicação com retrofit desta task
> - ajustar viewModel
> - ajustar usecase
> - ajustar data

### Layout - "Troque sua senha!"

> - [ ] Criar layout "Troque sua senha"
> - [ ] validar senha
> - Critérios
>      - dois numeros
>      - dois simbolos
>      - duas letras minusculas
>      - duas letras maiusculas
>      - minimo de 8 caracteres
>      - passar quando as senhas nos dois campos forem iguais.
> - [ ] Se são iguais, enviar senha criptografada para back-end 
>      - refatorar layout
> 
> - [ ] Criar a rota de comunicação com retrofit desta task
> - ajustar viewModel
> - ajustar usecase
> - ajustar data

**Comment by Marii-brito** [comment]
Obrigada, @gusoliveira21 !!
